jobs:
  publish:
    permissions:
      contents: write
      packages: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: adopt
        java-version: '8'
    - continue-on-error: true
      name: Set version
      run: mvn versions:set -DnewVersion=${{ github.ref_name }}
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Build jar
      run: mvn -B clean package -DskipTests
    - continue-on-error: true
      name: Rename artifact
      run: mv target/ysoserial-${{ github.ref_name }}-all.jar target/ysoserial-all.jar
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Publish GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: target/ysoserial-all.jar
name: publish jar
on:
  repository_dispatch:
    types: trigger-ga___publish.yml
permissions:
  contents: write
